-- require("origami").setup {
--   useLspFoldsWithTreesitterFallback = true, -- required for `autoFold`
--   pauseFoldsOnSearch = true,
--   foldtext = {
--     enabled = true,
--     padding = 3,
--     lineCount = {
--       template = "%d lines", -- `%d` is replaced with the number of folded lines
--       hlgroup = "Comment",
--     },
--     diagnosticsCount = true, -- uses hlgroups and icons from `vim.diagnostic.config().signs`
--     gitsignsCount = true,    -- requires `gitsigns.nvim`
--   },
--   autoFold = {
--     enabled = false,
--     kinds = { "comment" }, ---@type lsp.FoldingRangeKind[]
--   },
--   foldKeymaps = {
--     setup = true, -- modifies `h` and `l`
--     hOnlyOpensOnFirstColumn = false,
--   },
-- }
